interface IDietItem {
    productName: string;
    quantityEaten: number; 
    associatedFood: IProduct;
}

interface IProduct {
    Id: string;
    productName: string;
    photoUrl: string,
    energyIntake: number;
}

interface IUserConsumption {
    totalEnergyIntake: number;
    consumedItems: IDietItem[];
}

/**
 * Defines the shape of the store as generated by the combineReducer/persistCombineReducer method.
 */
interface IAppStore {
    hasLoadedProducts: boolean;
    availableProducts: IProduct[];
    userInfo: IUserConsumption;
    isLoading: boolean;
}

export { IDietItem, IProduct, IAppStore, IUserConsumption };